

//COMPILACION


//JAVA (LENGUAJE DE ALTO NIVEL) -> LENGUAJE DE MAQUINA (LENGUAJE DE BAJO NIVEL)  / 1 0 0 1

//TRANSPILAR

// ALTO -> ALTO
// BAJO -> BAJO

- ES6 // 2015 -NUEVAS FEACTURES  --- EXPLORER NO SE ACTUALIZA EL CHROME SI
- ES5 // < 2015  -- ES5 - EXPLORER 


// ES6 CON LAS FUNCIONES NUEVAS (X EJEM ARROWFUNCTION)DE ES6 Y SI LAS NECESITO EN IEXPLORER 
//TODO ESTO ES TRASPILAR
// ES6 -> ES5
//SASS -> CSS
// TYPESCRIPT -> JS

//BABEL ES UN TRASPILADOR

//npm i -D nodemon para que diga dev dependencia q solo lo instale para el que desarrolla y o el que la baja